### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by EEnayati** [TheDatumOrg/TSB-UAD#1] opened 2022-06-29 11:51 UTC
I tried to install the package with "pip install -r requirements.txt" but it seems there is a problem with numpy versions which different packages required. for example this error:
    The conflict is caused by:
    The user requested numpy==1.18.5
    arch 5.0.1 depends on numpy>=1.17
    h5py 2.10.0 depends on numpy>=1.7
    hurst 0.0.5 depends on numpy>=1.10
    matrixprofile 1.1.10 depends on numpy>=1.16.2
    pandas 1.3.3 depends on numpy>=1.17.3
    pmdarima 1.8.2 depends on numpy~=1.19.0

when I tried to fixed the error with another numpy version,  I faced with similar errors
![Uploading 19.png…]()
!

**Comment by johnpaparrizos** [comment] 2022-09-08 19:46
I believe the issue is now fixed. Please use the latest repo.

**Closed as completed** 2022-09-08 19:47 UTC
